<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4 Regression | Corpus Annotation and Data Analysis Equinox School: Introduction to Statistics</title>
  <meta name="description" content="This book introduces inferential statistics using R and is based on a class I taught at the University of Göttingen for the Corpus Annotation and Data Analysis equinox school in September 2022." />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="4 Regression | Corpus Annotation and Data Analysis Equinox School: Introduction to Statistics" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This book introduces inferential statistics using R and is based on a class I taught at the University of Göttingen for the Corpus Annotation and Data Analysis equinox school in September 2022." />
  <meta name="github-repo" content="mkthalmann" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Regression | Corpus Annotation and Data Analysis Equinox School: Introduction to Statistics" />
  
  <meta name="twitter:description" content="This book introduces inferential statistics using R and is based on a class I taught at the University of Göttingen for the Corpus Annotation and Data Analysis equinox school in September 2022." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="3-anova.html"/>
<link rel="next" href="5-linear-mixed-models.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">CAnDA Equinox School School: Introduction to Statistics</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i><b>1.1</b> Prerequisites</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#r"><i class="fa fa-check"></i><b>1.1.1</b> R</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#statistics"><i class="fa fa-check"></i><b>1.1.2</b> Statistics</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#get-in-touch"><i class="fa fa-check"></i><b>1.2</b> Get in touch</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#session-info"><i class="fa fa-check"></i>Session Info</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html"><i class="fa fa-check"></i><b>2</b> Concepts and Background</a>
<ul>
<li class="chapter" data-level="2.1" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#some-general-points-about-the-class"><i class="fa fa-check"></i><b>2.1</b> Some general points about the class</a></li>
<li class="chapter" data-level="2.2" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#on-inferential-statistics"><i class="fa fa-check"></i><b>2.2</b> On inferential statistics</a></li>
<li class="chapter" data-level="2.3" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#a-note-on-frequentism"><i class="fa fa-check"></i><b>2.3</b> A note on frequentism</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#measures-of-central-tendency"><i class="fa fa-check"></i><b>2.3.1</b> Measures of Central Tendency</a></li>
<li class="chapter" data-level="2.3.2" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#measures-of-dispersion"><i class="fa fa-check"></i><b>2.3.2</b> Measures of Dispersion</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#hypotheses"><i class="fa fa-check"></i><b>2.4</b> Hypotheses</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#null-hypothesis"><i class="fa fa-check"></i><b>2.4.1</b> Null Hypothesis</a></li>
<li class="chapter" data-level="2.4.2" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#alternative-hypothesis"><i class="fa fa-check"></i><b>2.4.2</b> Alternative hypothesis</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#type-i-and-type-ii-errors"><i class="fa fa-check"></i><b>2.5</b> Type I and Type II errors</a></li>
<li class="chapter" data-level="2.6" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#some-terms"><i class="fa fa-check"></i><b>2.6</b> Some terms</a></li>
<li class="chapter" data-level="2.7" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#the-t-test"><i class="fa fa-check"></i><b>2.7</b> The <span class="math inline">\(t\)</span>-test</a></li>
<li class="chapter" data-level="2.8" data-path="2-concepts-and-background.html"><a href="2-concepts-and-background.html#wrap-up"><i class="fa fa-check"></i><b>2.8</b> Wrap-Up</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-anova.html"><a href="3-anova.html"><i class="fa fa-check"></i><b>3</b> ANOVA</a>
<ul>
<li class="chapter" data-level="3.1" data-path="3-anova.html"><a href="3-anova.html#yesterday"><i class="fa fa-check"></i><b>3.1</b> Yesterday</a></li>
<li class="chapter" data-level="3.2" data-path="3-anova.html"><a href="3-anova.html#how-to-get-to-rome"><i class="fa fa-check"></i><b>3.2</b> How to get to Rome</a></li>
<li class="chapter" data-level="3.3" data-path="3-anova.html"><a href="3-anova.html#repeated-measures"><i class="fa fa-check"></i><b>3.3</b> Repeated Measures</a></li>
<li class="chapter" data-level="3.4" data-path="3-anova.html"><a href="3-anova.html#two-way-anova"><i class="fa fa-check"></i><b>3.4</b> Two-Way ANOVA</a></li>
<li class="chapter" data-level="3.5" data-path="3-anova.html"><a href="3-anova.html#more-repeated-measures"><i class="fa fa-check"></i><b>3.5</b> More repeated measures</a></li>
<li class="chapter" data-level="3.6" data-path="3-anova.html"><a href="3-anova.html#anova-by-hand"><i class="fa fa-check"></i><b>3.6</b> ANOVA by hand</a></li>
<li class="chapter" data-level="3.7" data-path="3-anova.html"><a href="3-anova.html#interpreting-an-anova"><i class="fa fa-check"></i><b>3.7</b> Interpreting an ANOVA</a></li>
<li class="chapter" data-level="3.8" data-path="3-anova.html"><a href="3-anova.html#wrap-up-1"><i class="fa fa-check"></i><b>3.8</b> Wrap-Up</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-regression.html"><a href="4-regression.html"><i class="fa fa-check"></i><b>4</b> Regression</a>
<ul>
<li class="chapter" data-level="4.1" data-path="4-regression.html"><a href="4-regression.html#models-and-regression-lines"><i class="fa fa-check"></i><b>4.1</b> Models and regression lines</a></li>
<li class="chapter" data-level="4.2" data-path="4-regression.html"><a href="4-regression.html#varying-intercepts-slopes-and-errors"><i class="fa fa-check"></i><b>4.2</b> Varying intercepts, slopes, and errors</a></li>
<li class="chapter" data-level="4.3" data-path="4-regression.html"><a href="4-regression.html#regression-in-r"><i class="fa fa-check"></i><b>4.3</b> Regression in R</a></li>
<li class="chapter" data-level="4.4" data-path="4-regression.html"><a href="4-regression.html#multiple-regression"><i class="fa fa-check"></i><b>4.4</b> Multiple Regression</a></li>
<li class="chapter" data-level="4.5" data-path="4-regression.html"><a href="4-regression.html#centering-and-standardization"><i class="fa fa-check"></i><b>4.5</b> Centering and Standardization</a></li>
<li class="chapter" data-level="4.6" data-path="4-regression.html"><a href="4-regression.html#interpreting-interactions"><i class="fa fa-check"></i><b>4.6</b> Interpreting interactions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-linear-mixed-models.html"><a href="5-linear-mixed-models.html"><i class="fa fa-check"></i><b>5</b> Linear Mixed Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="5-linear-mixed-models.html"><a href="5-linear-mixed-models.html#previously"><i class="fa fa-check"></i><b>5.1</b> Previously …</a></li>
<li class="chapter" data-level="5.2" data-path="5-linear-mixed-models.html"><a href="5-linear-mixed-models.html#before-we-go-on-lets-talk-about-pooling"><i class="fa fa-check"></i><b>5.2</b> Before we go on, let’s talk about pooling</a></li>
<li class="chapter" data-level="5.3" data-path="5-linear-mixed-models.html"><a href="5-linear-mixed-models.html#random-effects"><i class="fa fa-check"></i><b>5.3</b> Random Effects</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="5-linear-mixed-models.html"><a href="5-linear-mixed-models.html#lets-have-a-bit-more-of-a-detailed-look"><i class="fa fa-check"></i><b>5.3.1</b> Let’s have a bit more of a detailed look</a></li>
<li class="chapter" data-level="5.3.2" data-path="5-linear-mixed-models.html"><a href="5-linear-mixed-models.html#model-output-comparisons"><i class="fa fa-check"></i><b>5.3.2</b> Model output comparisons</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="5-linear-mixed-models.html"><a href="5-linear-mixed-models.html#what-do-i-do-about-my-p-values"><i class="fa fa-check"></i><b>5.4</b> What do I do about my <span class="math inline">\(p\)</span>-values?</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="6-loose-ends.html"><a href="6-loose-ends.html"><i class="fa fa-check"></i><b>6</b> Loose ends</a>
<ul>
<li class="chapter" data-level="6.1" data-path="6-loose-ends.html"><a href="6-loose-ends.html#long-computation-times"><i class="fa fa-check"></i><b>6.1</b> Long computation times</a></li>
<li class="chapter" data-level="6.2" data-path="6-loose-ends.html"><a href="6-loose-ends.html#convergence-issues"><i class="fa fa-check"></i><b>6.2</b> Convergence Issues</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="6-loose-ends.html"><a href="6-loose-ends.html#optimizers"><i class="fa fa-check"></i><b>6.2.1</b> Optimizers</a></li>
<li class="chapter" data-level="6.2.2" data-path="6-loose-ends.html"><a href="6-loose-ends.html#reducing-the-random-effects-structure"><i class="fa fa-check"></i><b>6.2.2</b> Reducing the random effects structure</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6-loose-ends.html"><a href="6-loose-ends.html#investigating-interactions-and-pairwise-comparisons"><i class="fa fa-check"></i><b>6.3</b> Investigating interactions and pairwise comparisons</a></li>
<li class="chapter" data-level="6.4" data-path="6-loose-ends.html"><a href="6-loose-ends.html#not-recommended-all-pairwise-comparisons"><i class="fa fa-check"></i><b>6.4</b> Not recommended: all pairwise comparisons</a></li>
<li class="chapter" data-level="6.5" data-path="6-loose-ends.html"><a href="6-loose-ends.html#more-emmeans-interactions"><i class="fa fa-check"></i><b>6.5</b> More emmeans: Interactions</a></li>
<li class="chapter" data-level="6.6" data-path="6-loose-ends.html"><a href="6-loose-ends.html#ordinal-data"><i class="fa fa-check"></i><b>6.6</b> Ordinal data</a></li>
<li class="chapter" data-level="6.7" data-path="6-loose-ends.html"><a href="6-loose-ends.html#reporting"><i class="fa fa-check"></i><b>6.7</b> Reporting</a></li>
<li class="chapter" data-level="6.8" data-path="6-loose-ends.html"><a href="6-loose-ends.html#open-questions"><i class="fa fa-check"></i><b>6.8</b> Open questions</a></li>
<li class="chapter" data-level="6.9" data-path="6-loose-ends.html"><a href="6-loose-ends.html#fin"><i class="fa fa-check"></i><b>6.9</b> Fin!</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="mailto:maik.thalmann@gmail.com?subject=[SummerSchool]%20" target="blank">maik.thalmann@gmail.com</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Corpus Annotation and Data Analysis Equinox School: Introduction to Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regression" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">4</span> Regression<a href="4-regression.html#regression" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="models-and-regression-lines" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Models and regression lines<a href="4-regression.html#models-and-regression-lines" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As we saw yesterday, ANOVAs and the LM are really close to each other. Both can be conceptualized as linear models that do most of their work by fitting a line.</p>
<p>We talked about this briefly yesterday, today we should dive into the theory a little bit more.</p>
<p>As you may remember from school, we can describe a line as follows, where <span class="math inline">\(b_0\)</span> is the intercept, <span class="math inline">\(b_1\)</span> the slope, and <span class="math inline">\(e\)</span> is the error term:</p>
<p><span class="math display">\[y = b_0 + b_1 + x + e\]</span></p>
<p>But let us take a step back first. Say this is our data:</p>
<p><img src="figs/lineqd-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>But this is just a representation, not a model.</p>
<p>For example, we could have a so-called intercept-only model. In these cases, the intercept is just the grand mean we saw in the ANOVA by hand portion yesterday:</p>
<p><span class="math display">\[y_i = \bar{y} + e_i\]</span></p>
<p>This model just says that our line maps each individual observation <span class="math inline">\(y_i\)</span> to the grand mean, <span class="math inline">\(\bar{y}\)</span> plus some error, where the error is the distance from the observation to the mean:</p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="4-regression.html#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(judgment <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> d_psp))</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = judgment ~ 1, data = d_psp)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.64688 -1.64688  0.35312  1.35312  1.35312 
## 
## Coefficients:
##             Estimate Std. Error t value              Pr(&gt;|t|)    
## (Intercept) 3.646880   0.056258  64.824 &lt; 0.00000000000000022 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.442 on 656 degrees of freedom</code></pre>
<p>In a plot, the line looks like this:</p>
<p><img src="figs/gmmodelp-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>But, of course, the mean is not a really interesting model.</p>
<p>In what is to come, we will have a look at more complex models and talk about how to interpret them.</p>
</div>
<div id="varying-intercepts-slopes-and-errors" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Varying intercepts, slopes, and errors<a href="4-regression.html#varying-intercepts-slopes-and-errors" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s familiarize ourselves with the graphical effects of changing intercepts, slopes, and errors.</p>
<p>As a first step, we manipulate only the intercepts of the lines, while keeping everything else constant. That is, the slope of the line should remain exactly the same.</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="4-regression.html#cb96-1" aria-hidden="true" tabindex="-1"></a>eq_0 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb96-2"><a href="4-regression.html#cb96-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> x</span>
<span id="cb96-3"><a href="4-regression.html#cb96-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb96-4"><a href="4-regression.html#cb96-4" aria-hidden="true" tabindex="-1"></a>eq_1 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb96-5"><a href="4-regression.html#cb96-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> x</span>
<span id="cb96-6"><a href="4-regression.html#cb96-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb96-7"><a href="4-regression.html#cb96-7" aria-hidden="true" tabindex="-1"></a>eq_2 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb96-8"><a href="4-regression.html#cb96-8" aria-hidden="true" tabindex="-1"></a>  <span class="dv">2</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> x</span>
<span id="cb96-9"><a href="4-regression.html#cb96-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb96-10"><a href="4-regression.html#cb96-10" aria-hidden="true" tabindex="-1"></a>base_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(eq) {</span>
<span id="cb96-11"><a href="4-regression.html#cb96-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">7</span>, <span class="dv">7</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb96-12"><a href="4-regression.html#cb96-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb96-13"><a href="4-regression.html#cb96-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_function</span>(<span class="at">fun =</span> eq, <span class="at">color =</span> colors[<span class="dv">1</span>]) <span class="sc">+</span></span>
<span id="cb96-14"><a href="4-regression.html#cb96-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>)) <span class="sc">+</span></span>
<span id="cb96-15"><a href="4-regression.html#cb96-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;grey&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb96-16"><a href="4-regression.html#cb96-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb96-17"><a href="4-regression.html#cb96-17" aria-hidden="true" tabindex="-1"></a>p_0 <span class="ot">&lt;-</span> <span class="fu">base_plot</span>(eq_0)</span>
<span id="cb96-18"><a href="4-regression.html#cb96-18" aria-hidden="true" tabindex="-1"></a>p_1 <span class="ot">&lt;-</span> <span class="fu">base_plot</span>(eq_1)</span>
<span id="cb96-19"><a href="4-regression.html#cb96-19" aria-hidden="true" tabindex="-1"></a>p_2 <span class="ot">&lt;-</span> <span class="fu">base_plot</span>(eq_2)</span>
<span id="cb96-20"><a href="4-regression.html#cb96-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-21"><a href="4-regression.html#cb96-21" aria-hidden="true" tabindex="-1"></a>p_0 <span class="sc">/</span> p_1 <span class="sc">/</span> p_2</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:intercepts"></span>
<img src="figs/intercepts-1.png" alt="Varying slopes." width="100%" />
<p class="caption">
Figure 4.1: Varying slopes.
</p>
</div>
<p>Below, I keep the intercepts constant (at <span class="math inline">\(0\)</span>) and vary only the slopes:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="4-regression.html#cb97-1" aria-hidden="true" tabindex="-1"></a>eq_0 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb97-2"><a href="4-regression.html#cb97-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">0</span> <span class="sc">+</span> <span class="dv">0</span> <span class="sc">*</span> x</span>
<span id="cb97-3"><a href="4-regression.html#cb97-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb97-4"><a href="4-regression.html#cb97-4" aria-hidden="true" tabindex="-1"></a>eq_1 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb97-5"><a href="4-regression.html#cb97-5" aria-hidden="true" tabindex="-1"></a>  <span class="dv">0</span> <span class="sc">+</span> <span class="dv">1</span> <span class="sc">*</span> x</span>
<span id="cb97-6"><a href="4-regression.html#cb97-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb97-7"><a href="4-regression.html#cb97-7" aria-hidden="true" tabindex="-1"></a>eq_2 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb97-8"><a href="4-regression.html#cb97-8" aria-hidden="true" tabindex="-1"></a>  <span class="dv">0</span> <span class="sc">+</span> <span class="dv">2</span> <span class="sc">*</span> x</span>
<span id="cb97-9"><a href="4-regression.html#cb97-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb97-10"><a href="4-regression.html#cb97-10" aria-hidden="true" tabindex="-1"></a>base_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(eq) {</span>
<span id="cb97-11"><a href="4-regression.html#cb97-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">7</span>, <span class="dv">7</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb97-12"><a href="4-regression.html#cb97-12" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> x)) <span class="sc">+</span></span>
<span id="cb97-13"><a href="4-regression.html#cb97-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">stat_function</span>(<span class="at">fun =</span> eq, <span class="at">color =</span> colors[<span class="dv">1</span>]) <span class="sc">+</span></span>
<span id="cb97-14"><a href="4-regression.html#cb97-14" aria-hidden="true" tabindex="-1"></a>    <span class="fu">coord_cartesian</span>(<span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">7</span>)) <span class="sc">+</span></span>
<span id="cb97-15"><a href="4-regression.html#cb97-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">&quot;grey&quot;</span>, <span class="at">lty =</span> <span class="st">&quot;dashed&quot;</span>)</span>
<span id="cb97-16"><a href="4-regression.html#cb97-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb97-17"><a href="4-regression.html#cb97-17" aria-hidden="true" tabindex="-1"></a>p_0 <span class="ot">&lt;-</span> <span class="fu">base_plot</span>(eq_0)</span>
<span id="cb97-18"><a href="4-regression.html#cb97-18" aria-hidden="true" tabindex="-1"></a>p_1 <span class="ot">&lt;-</span> <span class="fu">base_plot</span>(eq_1)</span>
<span id="cb97-19"><a href="4-regression.html#cb97-19" aria-hidden="true" tabindex="-1"></a>p_2 <span class="ot">&lt;-</span> <span class="fu">base_plot</span>(eq_2)</span>
<span id="cb97-20"><a href="4-regression.html#cb97-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-21"><a href="4-regression.html#cb97-21" aria-hidden="true" tabindex="-1"></a>p_0 <span class="sc">/</span> p_1 <span class="sc">/</span> p_2</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:slopes"></span>
<img src="figs/slopes-1.png" alt="Varying slopes." width="100%" />
<p class="caption">
Figure 4.2: Varying slopes.
</p>
</div>
<p>And here I vary the errors. In the first plot, <span class="math inline">\(x\)</span> predicts <span class="math inline">\(y\)</span> perfectly, in the second, there is some noise.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="4-regression.html#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb98-2"><a href="4-regression.html#cb98-2" aria-hidden="true" tabindex="-1"></a>base_plot <span class="ot">&lt;-</span> <span class="cf">function</span>(error) {</span>
<span id="cb98-3"><a href="4-regression.html#cb98-3" aria-hidden="true" tabindex="-1"></a>  x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">50</span>)</span>
<span id="cb98-4"><a href="4-regression.html#cb98-4" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="dv">5</span> <span class="sc">+</span> <span class="dv">3</span> <span class="sc">*</span> x <span class="sc">+</span> error</span>
<span id="cb98-5"><a href="4-regression.html#cb98-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">x =</span> x, <span class="at">y =</span> y) <span class="sc">%&gt;%</span></span>
<span id="cb98-6"><a href="4-regression.html#cb98-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb98-7"><a href="4-regression.html#cb98-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> colors[<span class="dv">1</span>]) <span class="sc">+</span></span>
<span id="cb98-8"><a href="4-regression.html#cb98-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>)</span>
<span id="cb98-9"><a href="4-regression.html#cb98-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb98-10"><a href="4-regression.html#cb98-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-11"><a href="4-regression.html#cb98-11" aria-hidden="true" tabindex="-1"></a>p_0 <span class="ot">&lt;-</span> <span class="fu">base_plot</span>(<span class="fu">rep</span>(<span class="dv">0</span>, <span class="dv">50</span>))</span>
<span id="cb98-12"><a href="4-regression.html#cb98-12" aria-hidden="true" tabindex="-1"></a>p_1 <span class="ot">&lt;-</span> <span class="fu">base_plot</span>(<span class="fu">rnorm</span>(<span class="dv">50</span>))</span>
<span id="cb98-13"><a href="4-regression.html#cb98-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb98-14"><a href="4-regression.html#cb98-14" aria-hidden="true" tabindex="-1"></a>p_0 <span class="sc">/</span> p_1</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:errors"></span>
<img src="figs/errors-1.png" alt="Varying error terms." width="100%" />
<p class="caption">
Figure 4.3: Varying error terms.
</p>
</div>
<p>Note that the errors are also a part of the unsystematic variance we talked about. They represent deviations from our prediction that cannot be explained by our model. These errors, as said before, are also called <strong>residuals</strong>.</p>
</div>
<div id="regression-in-r" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Regression in R<a href="4-regression.html#regression-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here is some data from <a href="http://www3.dsi.uminho.pt/pcortez/student.pdf">this paper</a>.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="4-regression.html#cb99-1" aria-hidden="true" tabindex="-1"></a>students <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="fu">here</span>(<span class="st">&quot;assets&quot;</span>, <span class="st">&quot;data&quot;</span>, <span class="st">&quot;student-mat.csv&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb99-2"><a href="4-regression.html#cb99-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(G3, sex, age, studytime)</span>
<span id="cb99-3"><a href="4-regression.html#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(students)</span></code></pre></div>
<pre><code>##   G3 sex age studytime
## 1  6   F  18         2
## 2  6   F  17         2
## 3 10   F  15         2
## 4 15   F  15         3
## 5 10   F  16         2
## 6 15   M  16         2</code></pre>
<p>Let’s again compute a <span class="math inline">\(t\)</span>-test to see whether there are any differences on the G3 scores by sex:</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="4-regression.html#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(G3 <span class="sc">~</span> sex, <span class="at">data =</span> students, <span class="at">paired =</span> <span class="cn">FALSE</span>, <span class="at">var.equal =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb101-2"><a href="4-regression.html#cb101-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>()</span></code></pre></div>
<pre><code>## # A tibble: 1 × 10
##   estimate estimate1 estimate2 statistic p.value parameter conf.low conf.high method            alternative
##      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;             &lt;chr&gt;      
## 1   -0.948      9.97      10.9     -2.06  0.0399       393    -1.85   -0.0441 Two Sample t-test two.sided</code></pre>
<p>Once again, in this simple case, the <span class="math inline">\(t\)</span>-test is equivalent to the linear regression (called using the <code>lm()</code> function):</p>
<div class="sourceCode" id="cb103"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb103-1"><a href="4-regression.html#cb103-1" aria-hidden="true" tabindex="-1"></a>m_students <span class="ot">&lt;-</span> <span class="fu">lm</span>(G3 <span class="sc">~</span> sex, <span class="at">data =</span> students)</span>
<span id="cb103-2"><a href="4-regression.html#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m_students) <span class="sc">%&gt;%</span></span>
<span id="cb103-3"><a href="4-regression.html#cb103-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb103-4"><a href="4-regression.html#cb103-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">p.value =</span> scales<span class="sc">::</span><span class="fu">pvalue</span>(p.value))</span></code></pre></div>
<pre><code>## # A tibble: 2 × 5
##   term        estimate std.error statistic p.value
##   &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;  
## 1 (Intercept)    9.97      0.316     31.5  &lt;0.001 
## 2 sexM           0.948     0.460      2.06 0.040</code></pre>
<p>The line intercepts the <span class="math inline">\(y\)</span> axis at <span class="math inline">\(\sim9.9\)</span>. As you change the <span class="math inline">\(x\)</span>-axis value by <span class="math inline">\(1\)</span> (which represents our change from female to male because of the way the predictor was represented), the slope of the line changes by <span class="math inline">\(\sim 0.94\)</span>.</p>
<p>In effect, everything else being equal, male students have higher G3 scores than women.</p>
<p>But let’s also check if we can see the coefficients that the <code>lm()</code> computed in a plot. To generate the line, I use the <code>geom_smooth()</code> (with <code>method = "lm"</code>) function:</p>
<div class="sourceCode" id="cb105"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="4-regression.html#cb105-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span></span>
<span id="cb105-2"><a href="4-regression.html#cb105-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">if_else</span>(sex <span class="sc">==</span> <span class="st">&quot;F&quot;</span>, <span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb105-3"><a href="4-regression.html#cb105-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> sex, <span class="at">y =</span> G3)) <span class="sc">+</span></span>
<span id="cb105-4"><a href="4-regression.html#cb105-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb105-5"><a href="4-regression.html#cb105-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> colors[<span class="dv">1</span>]) <span class="sc">+</span></span>
<span id="cb105-6"><a href="4-regression.html#cb105-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="at">color =</span> colors[<span class="dv">1</span>], <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb105-7"><a href="4-regression.html#cb105-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> scales<span class="sc">::</span><span class="fu">breaks_extended</span>(<span class="at">n =</span> <span class="dv">18</span>)) <span class="sc">+</span></span>
<span id="cb105-8"><a href="4-regression.html#cb105-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span></code></pre></div>
<p><img src="figs/studentsp-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>As we can (hopefully) see, the intercept that the model predicts is exactly the mean for the women (coded here 0, more on that later). And if we subtract the condition mean of the men with that of the women, we are left with the predicted slope.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="4-regression.html#cb106-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span></span>
<span id="cb106-2"><a href="4-regression.html#cb106-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(sex) <span class="sc">%&gt;%</span></span>
<span id="cb106-3"><a href="4-regression.html#cb106-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb106-4"><a href="4-regression.html#cb106-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">mean =</span> <span class="fu">mean</span>(G3)</span>
<span id="cb106-5"><a href="4-regression.html#cb106-5" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 2 × 2
##   sex    mean
##   &lt;chr&gt; &lt;dbl&gt;
## 1 F      9.97
## 2 M     10.9</code></pre>
<p>So, essentially what we do when we use the tests we’ve looked at so far is line fitting.</p>
<p>We will walk trough a few other cases to see what’s going on when we increase the complexity.</p>
</div>
<div id="multiple-regression" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Multiple Regression<a href="4-regression.html#multiple-regression" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In multiple regression, we simply add more slopes, while the intercept is now dependent on multiple variables:</p>
<p><span class="math display">\[y = b_0 + b_1x + b_2x + ... + e\]</span>
Here is the student data again:</p>
<div class="sourceCode" id="cb108"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="4-regression.html#cb108-1" aria-hidden="true" tabindex="-1"></a>students_mult <span class="ot">&lt;-</span> <span class="fu">lm</span>(G3 <span class="sc">~</span> age <span class="sc">+</span> sex, <span class="at">data =</span> students)</span>
<span id="cb108-2"><a href="4-regression.html#cb108-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(students_mult)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = G3 ~ age + sex, data = students)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -11.85931  -1.85931   0.28063   3.14069   9.75707 
## 
## Coefficients:
##             Estimate Std. Error t value        Pr(&gt;|t|)    
## (Intercept) 19.50235    2.99661  6.5081 0.0000000002329 ***
## age         -0.56997    0.17813 -3.1997        0.001488 ** 
## sexM         0.90648    0.45467  1.9937        0.046877 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.51 on 392 degrees of freedom
## Multiple R-squared:  0.035884,   Adjusted R-squared:  0.030965 
## F-statistic:  7.295 on 2 and 392 DF,  p-value: 0.00077507</code></pre>
<p>Let’s plot the data and see what the lines look like. Below I explicitly extract the coefficients from the lm object for illustrative purposes:</p>
<div class="sourceCode" id="cb110"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="4-regression.html#cb110-1" aria-hidden="true" tabindex="-1"></a>equation1 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb110-2"><a href="4-regression.html#cb110-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(students_mult)[<span class="dv">2</span>] <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">coef</span>(students_mult)[<span class="dv">1</span>]</span>
<span id="cb110-3"><a href="4-regression.html#cb110-3" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb110-4"><a href="4-regression.html#cb110-4" aria-hidden="true" tabindex="-1"></a>equation2 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb110-5"><a href="4-regression.html#cb110-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coef</span>(students_mult)[<span class="dv">2</span>] <span class="sc">*</span> x <span class="sc">+</span> <span class="fu">coef</span>(students_mult)[<span class="dv">1</span>] <span class="sc">+</span> <span class="fu">coef</span>(students_mult)[<span class="dv">3</span>]</span>
<span id="cb110-6"><a href="4-regression.html#cb110-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb110-7"><a href="4-regression.html#cb110-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb110-8"><a href="4-regression.html#cb110-8" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span></span>
<span id="cb110-9"><a href="4-regression.html#cb110-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(</span>
<span id="cb110-10"><a href="4-regression.html#cb110-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> age,</span>
<span id="cb110-11"><a href="4-regression.html#cb110-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> G3,</span>
<span id="cb110-12"><a href="4-regression.html#cb110-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> sex,</span>
<span id="cb110-13"><a href="4-regression.html#cb110-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">group =</span> sex,</span>
<span id="cb110-14"><a href="4-regression.html#cb110-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">pch =</span> sex</span>
<span id="cb110-15"><a href="4-regression.html#cb110-15" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb110-16"><a href="4-regression.html#cb110-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb110-17"><a href="4-regression.html#cb110-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb110-18"><a href="4-regression.html#cb110-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(</span>
<span id="cb110-19"><a href="4-regression.html#cb110-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> equation1,</span>
<span id="cb110-20"><a href="4-regression.html#cb110-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="at">color =</span> colors[<span class="dv">1</span>]</span>
<span id="cb110-21"><a href="4-regression.html#cb110-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb110-22"><a href="4-regression.html#cb110-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_function</span>(</span>
<span id="cb110-23"><a href="4-regression.html#cb110-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">fun =</span> equation2,</span>
<span id="cb110-24"><a href="4-regression.html#cb110-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="at">color =</span> colors[<span class="dv">2</span>]</span>
<span id="cb110-25"><a href="4-regression.html#cb110-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb110-26"><a href="4-regression.html#cb110-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb110-27"><a href="4-regression.html#cb110-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> scales<span class="sc">::</span><span class="fu">breaks_extended</span>(<span class="at">n =</span> <span class="dv">18</span>)) <span class="sc">+</span></span>
<span id="cb110-28"><a href="4-regression.html#cb110-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> colors)</span></code></pre></div>
<p><img src="figs/studentsmultplot-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>And now let’s add an interaction term:</p>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="4-regression.html#cb111-1" aria-hidden="true" tabindex="-1"></a>students_mult_int <span class="ot">&lt;-</span> <span class="fu">lm</span>(G3 <span class="sc">~</span> age <span class="sc">*</span> sex, <span class="at">data =</span> students)</span>
<span id="cb111-2"><a href="4-regression.html#cb111-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(students_mult_int)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = G3 ~ age * sex, data = students)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -12.40927  -1.70410   0.39417   2.89459  10.09934 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept) 13.15019    4.35878  3.0169  0.00272 **
## age         -0.19030    0.25986 -0.7323  0.46441   
## sexM        12.78493    5.95646  2.1464  0.03246 * 
## age:sexM    -0.71142    0.35571 -2.0000  0.04619 * 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.4928 on 391 degrees of freedom
## Multiple R-squared:  0.045647,   Adjusted R-squared:  0.038325 
## F-statistic: 6.2339 on 3 and 391 DF,  p-value: 0.00038297</code></pre>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="4-regression.html#cb113-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span></span>
<span id="cb113-2"><a href="4-regression.html#cb113-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> G3, <span class="at">color =</span> sex, <span class="at">pch =</span> sex, <span class="at">group =</span> sex)) <span class="sc">+</span></span>
<span id="cb113-3"><a href="4-regression.html#cb113-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb113-4"><a href="4-regression.html#cb113-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb113-5"><a href="4-regression.html#cb113-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb113-6"><a href="4-regression.html#cb113-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> scales<span class="sc">::</span><span class="fu">breaks_extended</span>(<span class="at">n =</span> <span class="dv">16</span>)) <span class="sc">+</span></span>
<span id="cb113-7"><a href="4-regression.html#cb113-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlim</span>(<span class="dv">0</span>, <span class="dv">25</span>) <span class="sc">+</span></span>
<span id="cb113-8"><a href="4-regression.html#cb113-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> colors)</span></code></pre></div>
<p><img src="figs/studentsmultplotint-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Here is an example equation for a regression with two predictors and an interaction term (without the error):</p>
<p><span class="math display">\[y = b_0 + b_1x_1 + b_2x_2 + b_3(x_1 * x_2)\]</span></p>
<p>As you see here, the interaction term estimates a multiplicative effect for the two predictors. As with the main effects, if <span class="math inline">\(b_3\)</span> is close to zero, the interaction is small.</p>
</div>
<div id="centering-and-standardization" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Centering and Standardization<a href="4-regression.html#centering-and-standardization" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Here is a small illustration of scaling/transforming, centering, and standardization.</p>
<p>Centering simply involves subtracting the mean from the individual observations. This will give a new meaning to the intercept, which will now represent the overall mean of the dependent variable, rather than its value at predictor = 0.</p>
<p>In formula-talk, we could represent a centered predictor like this:</p>
<p><span class="math display">\[y = b_0 + b_1(x - \bar{x}) + e\]</span>
Let’s what happens when we center the age predictor below.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="4-regression.html#cb114-1" aria-hidden="true" tabindex="-1"></a>students <span class="ot">&lt;-</span> students <span class="sc">%&gt;%</span></span>
<span id="cb114-2"><a href="4-regression.html#cb114-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb114-3"><a href="4-regression.html#cb114-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_bar =</span> <span class="fu">mean</span>(age),</span>
<span id="cb114-4"><a href="4-regression.html#cb114-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_c =</span> age <span class="sc">-</span> age_bar <span class="co"># alternative: scale(., scale = FALSE)</span></span>
<span id="cb114-5"><a href="4-regression.html#cb114-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb114-6"><a href="4-regression.html#cb114-6" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span></span>
<span id="cb114-7"><a href="4-regression.html#cb114-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(G3, age, age_c, age_bar) <span class="sc">%&gt;%</span></span>
<span id="cb114-8"><a href="4-regression.html#cb114-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   G3 age       age_c   age_bar
## 1  6  18  1.30379747 16.696203
## 2  6  17  0.30379747 16.696203
## 3 10  15 -1.69620253 16.696203
## 4 15  15 -1.69620253 16.696203
## 5 10  16 -0.69620253 16.696203
## 6 15  16 -0.69620253 16.696203</code></pre>
<div class="sourceCode" id="cb116"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="4-regression.html#cb116-1" aria-hidden="true" tabindex="-1"></a>students_c <span class="ot">&lt;-</span> <span class="fu">lm</span>(G3 <span class="sc">~</span> age_c, <span class="at">data =</span> students)</span>
<span id="cb116-2"><a href="4-regression.html#cb116-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(students_c)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = G3 ~ age_c, data = students)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -11.39920  -1.65882   0.34118   3.18092   9.50143 
## 
## Coefficients:
##             Estimate Std. Error t value              Pr(&gt;|t|)    
## (Intercept) 10.41519    0.22778 45.7253 &lt; 0.00000000000000022 ***
## age_c       -0.58013    0.17873 -3.2458              0.001271 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 4.527 on 393 degrees of freedom
## Multiple R-squared:  0.026108,   Adjusted R-squared:  0.02363 
## F-statistic: 10.535 on 1 and 393 DF,  p-value: 0.0012714</code></pre>
<div class="sourceCode" id="cb118"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb118-1"><a href="4-regression.html#cb118-1" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span></span>
<span id="cb118-2"><a href="4-regression.html#cb118-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sex =</span> <span class="fu">if_else</span>(sex <span class="sc">==</span> <span class="st">&quot;F&quot;</span>, <span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb118-3"><a href="4-regression.html#cb118-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> age_c, <span class="at">y =</span> G3)) <span class="sc">+</span></span>
<span id="cb118-4"><a href="4-regression.html#cb118-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb118-5"><a href="4-regression.html#cb118-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">color =</span> colors[<span class="dv">1</span>]) <span class="sc">+</span></span>
<span id="cb118-6"><a href="4-regression.html#cb118-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">geom =</span> <span class="st">&quot;line&quot;</span>, <span class="at">color =</span> colors[<span class="dv">1</span>], <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">fullrange =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb118-7"><a href="4-regression.html#cb118-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> scales<span class="sc">::</span><span class="fu">breaks_extended</span>(<span class="at">n =</span> <span class="dv">18</span>))</span></code></pre></div>
<p><img src="figs/studentscenterlmp-1.png" width="100%" style="display: block; margin: auto;" /></p>
<div class="alert alert-info">
<p><strong>Question:</strong> Why does it make sense in this case to center the age predictor? Does it help interpreting the model at all? Why?</p>
</div>
<p>We call centering a linear transformation because all values are affected in the same way. Adding 2 to every value would also be linear, for example.</p>
<p>Here’s another linear transformation, the so-called <span class="math inline">\(z\)</span> transformation. What we do here is to take the centered value and divide it by the standard deviation of the centered variable. This turns all of our values into ones from a distribution with <span class="math inline">\(\bar{x} \approx 0\)</span> and <span class="math inline">\(s = 1\)</span>.</p>
<div class="sourceCode" id="cb119"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="4-regression.html#cb119-1" aria-hidden="true" tabindex="-1"></a>students <span class="ot">&lt;-</span> students <span class="sc">%&gt;%</span></span>
<span id="cb119-2"><a href="4-regression.html#cb119-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb119-3"><a href="4-regression.html#cb119-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_z =</span> age_c <span class="sc">/</span> <span class="fu">sd</span>(age_c), <span class="co"># alternative: scale(.)</span></span>
<span id="cb119-4"><a href="4-regression.html#cb119-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_z_bar =</span> <span class="fu">mean</span>(age_z),</span>
<span id="cb119-5"><a href="4-regression.html#cb119-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">age_z_s =</span> <span class="fu">sd</span>(age_z)</span>
<span id="cb119-6"><a href="4-regression.html#cb119-6" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb119-7"><a href="4-regression.html#cb119-7" aria-hidden="true" tabindex="-1"></a>students <span class="sc">%&gt;%</span></span>
<span id="cb119-8"><a href="4-regression.html#cb119-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(G3, age, age_c, age_bar, age_z, age_z_bar, age_z_s) <span class="sc">%&gt;%</span></span>
<span id="cb119-9"><a href="4-regression.html#cb119-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   G3 age       age_c   age_bar       age_z                age_z_bar age_z_s
## 1  6  18  1.30379747 16.696203  1.02175064 0.0000000000000012813074       1
## 2  6  17  0.30379747 16.696203  0.23807782 0.0000000000000012813074       1
## 3 10  15 -1.69620253 16.696203 -1.32926782 0.0000000000000012813074       1
## 4 15  15 -1.69620253 16.696203 -1.32926782 0.0000000000000012813074       1
## 5 10  16 -0.69620253 16.696203 -0.54559500 0.0000000000000012813074       1
## 6 15  16 -0.69620253 16.696203 -0.54559500 0.0000000000000012813074       1</code></pre>
<div class="alert alert-info">
<p><strong>Question:</strong> What could be the upshot of such an operation? Maybe try to think of predictors other than age.</p>
</div>
<p>While a log transformation is non-linear because it affects larger values more strongly than it does smaller ones (and thus serves to cure positive skew), centering and standardization are both linear transformations that affect all observations in the same way.</p>
<div class="sourceCode" id="cb121"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="4-regression.html#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(diamonds<span class="sc">$</span>price)</span></code></pre></div>
<pre><code>## [1]   326 18823</code></pre>
<div class="sourceCode" id="cb123"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="4-regression.html#cb123-1" aria-hidden="true" tabindex="-1"></a>diamonds_scaled <span class="ot">&lt;-</span> diamonds <span class="sc">%&gt;%</span></span>
<span id="cb123-2"><a href="4-regression.html#cb123-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(carat, price) <span class="sc">%&gt;%</span></span>
<span id="cb123-3"><a href="4-regression.html#cb123-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb123-4"><a href="4-regression.html#cb123-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">price_log10 =</span> <span class="fu">log10</span>(price),</span>
<span id="cb123-5"><a href="4-regression.html#cb123-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">price_log10_c =</span> price_log10 <span class="sc">-</span> <span class="fu">mean</span>(price_log10), <span class="co"># or: scale(., scale = F)</span></span>
<span id="cb123-6"><a href="4-regression.html#cb123-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">price_log10_z =</span> price_log10_c <span class="sc">/</span> <span class="fu">sd</span>(price_log10_c) <span class="co"># or: scale(.)</span></span>
<span id="cb123-7"><a href="4-regression.html#cb123-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<div class="sourceCode" id="cb124"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb124-1"><a href="4-regression.html#cb124-1" aria-hidden="true" tabindex="-1"></a>diamonds_scaled <span class="sc">%&gt;%</span></span>
<span id="cb124-2"><a href="4-regression.html#cb124-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb124-3"><a href="4-regression.html#cb124-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> price), <span class="at">fill =</span> colors[<span class="dv">1</span>]) <span class="sc">+</span></span>
<span id="cb124-4"><a href="4-regression.html#cb124-4" aria-hidden="true" tabindex="-1"></a>  diamonds_scaled <span class="sc">%&gt;%</span></span>
<span id="cb124-5"><a href="4-regression.html#cb124-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb124-6"><a href="4-regression.html#cb124-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> price_log10), <span class="at">fill =</span> colors[<span class="dv">1</span>]) <span class="sc">+</span></span>
<span id="cb124-7"><a href="4-regression.html#cb124-7" aria-hidden="true" tabindex="-1"></a>  diamonds_scaled <span class="sc">%&gt;%</span></span>
<span id="cb124-8"><a href="4-regression.html#cb124-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb124-9"><a href="4-regression.html#cb124-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> price_log10_c), <span class="at">fill =</span> colors[<span class="dv">1</span>]) <span class="sc">+</span></span>
<span id="cb124-10"><a href="4-regression.html#cb124-10" aria-hidden="true" tabindex="-1"></a>  diamonds_scaled <span class="sc">%&gt;%</span></span>
<span id="cb124-11"><a href="4-regression.html#cb124-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb124-12"><a href="4-regression.html#cb124-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> price_log10_z), <span class="at">fill =</span> colors[<span class="dv">1</span>])</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:scale-comparison"></span>
<img src="figs/scale-comparison-1.png" alt="Comparison of raw prices with scaled and transformed values." width="100%" />
<p class="caption">
Figure 4.4: Comparison of raw prices with scaled and transformed values.
</p>
</div>
<p>Note that the output of the Pearson correlation function <code>cor</code> is exactly identical to the slope estimated by a linear regression with one predictor when both <span class="math inline">\(y\)</span> and <span class="math inline">\(x\)</span> are z-scores:</p>
<div class="sourceCode" id="cb125"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="4-regression.html#cb125-1" aria-hidden="true" tabindex="-1"></a>diamonds_scaled <span class="ot">&lt;-</span> diamonds_scaled <span class="sc">%&gt;%</span></span>
<span id="cb125-2"><a href="4-regression.html#cb125-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb125-3"><a href="4-regression.html#cb125-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">carat_log10_z =</span> <span class="fu">scale</span>(<span class="fu">log10</span>(carat))</span>
<span id="cb125-4"><a href="4-regression.html#cb125-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb125-5"><a href="4-regression.html#cb125-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb125-6"><a href="4-regression.html#cb125-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(diamonds_scaled<span class="sc">$</span>price_log10_z, diamonds_scaled<span class="sc">$</span>carat_log10_z)</span></code></pre></div>
<pre><code>##            [,1]
## [1,] 0.96591372</code></pre>
<div class="sourceCode" id="cb127"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb127-1"><a href="4-regression.html#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="co"># -1 removes the intercept computation, we know it&#39;s zero because of z-scores</span></span>
<span id="cb127-2"><a href="4-regression.html#cb127-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(price_log10_z <span class="sc">~</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> carat_log10_z, <span class="at">data =</span> diamonds_scaled)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price_log10_z ~ -1 + carat_log10_z, data = diamonds_scaled)
## 
## Coefficients:
## carat_log10_z  
##       0.96591</code></pre>
<p>In the plots below, we have some interactions:</p>
<ul>
<li><em>Above</em>: main effect possibilities without interactions</li>
<li><em>below</em>: including interactions – main effects determined by means, interactions by slopes.</li>
<li><em>Ltr/ttb</em>: no main effect, main effect for <span class="math inline">\(x\)</span> factor, split factor main effect, main effects for both, no main effect but interaction, <span class="math inline">\(x\)</span> factor effect plus interaction, split factor effect plus interaction, two main effects plus interaction.</li>
</ul>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:interactions"></span>
<img src="figs/interactions-1.png" alt="Interactions" width="100%" />
<p class="caption">
Figure 4.5: Interactions
</p>
</div>
</div>
<div id="interpreting-interactions" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Interpreting interactions<a href="4-regression.html#interpreting-interactions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Interactions make interpretation hard. Let’s see what there is to do.</p>
<p>Here is the simple pricing model with two predictors. The first is continuous, and gives us as indication about the weight of the diamonds. The second is categorical and gives us color information.</p>
<p>Here, we use treatment contrasts.</p>
<div class="sourceCode" id="cb129"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="4-regression.html#cb129-1" aria-hidden="true" tabindex="-1"></a>diamonds_sub <span class="ot">&lt;-</span> diamonds <span class="sc">%&gt;%</span></span>
<span id="cb129-2"><a href="4-regression.html#cb129-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(carat, price, color) <span class="sc">%&gt;%</span></span>
<span id="cb129-3"><a href="4-regression.html#cb129-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(color <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;E&quot;</span>, <span class="st">&quot;J&quot;</span>))</span>
<span id="cb129-4"><a href="4-regression.html#cb129-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-5"><a href="4-regression.html#cb129-5" aria-hidden="true" tabindex="-1"></a><span class="co"># this does not do much here, because R automatically uses treatment coding</span></span>
<span id="cb129-6"><a href="4-regression.html#cb129-6" aria-hidden="true" tabindex="-1"></a><span class="co"># but it helps to be explicit about this</span></span>
<span id="cb129-7"><a href="4-regression.html#cb129-7" aria-hidden="true" tabindex="-1"></a>diamonds_sub<span class="sc">$</span>color <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(diamonds_sub<span class="sc">$</span>color)</span>
<span id="cb129-8"><a href="4-regression.html#cb129-8" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(diamonds_sub<span class="sc">$</span>color) <span class="ot">&lt;-</span> <span class="fu">contr.treatment</span>(<span class="dv">2</span>)</span>
<span id="cb129-9"><a href="4-regression.html#cb129-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb129-10"><a href="4-regression.html#cb129-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(price <span class="sc">~</span> carat <span class="sc">+</span> color, diamonds_sub)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = price ~ carat + color, data = diamonds_sub)
## 
## Coefficients:
## (Intercept)        carat       color2  
##     -2042.5       7781.5      -1676.9</code></pre>
<p>Let’s clean up the output of the <code>lm()</code> command a bit. The <code>tidy()</code> function from the <code>broom</code> package gives us a dataframe, rather than the onslaught of text we saw above.</p>
<p>This is a little bit nicer to read:</p>
<div class="sourceCode" id="cb131"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb131-1"><a href="4-regression.html#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the broom package</span></span>
<span id="cb131-2"><a href="4-regression.html#cb131-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb131-3"><a href="4-regression.html#cb131-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-4"><a href="4-regression.html#cb131-4" aria-hidden="true" tabindex="-1"></a>lm_diam_twopred <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat <span class="sc">+</span> color, diamonds_sub)</span>
<span id="cb131-5"><a href="4-regression.html#cb131-5" aria-hidden="true" tabindex="-1"></a>lm_diam_twopred <span class="sc">%&gt;%</span></span>
<span id="cb131-6"><a href="4-regression.html#cb131-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb131-7"><a href="4-regression.html#cb131-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   term        estimate
##   &lt;chr&gt;          &lt;dbl&gt;
## 1 (Intercept)   -2042.
## 2 carat          7782.
## 3 color2        -1677.</code></pre>
<p>Let’s compare this to a model with an interaction term (where we replace <code>+</code> with <code>*</code> in the formula of the the <code>lm()</code> function call):</p>
<div class="sourceCode" id="cb133"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="4-regression.html#cb133-1" aria-hidden="true" tabindex="-1"></a>lm_diam_twopredint <span class="ot">&lt;-</span> <span class="fu">lm</span>(price <span class="sc">~</span> carat <span class="sc">*</span> color, diamonds_sub)</span>
<span id="cb133-2"><a href="4-regression.html#cb133-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb133-3"><a href="4-regression.html#cb133-3" aria-hidden="true" tabindex="-1"></a>lm_diam_twopredint <span class="sc">%&gt;%</span></span>
<span id="cb133-4"><a href="4-regression.html#cb133-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb133-5"><a href="4-regression.html#cb133-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 2
##   term         estimate
##   &lt;chr&gt;           &lt;dbl&gt;
## 1 (Intercept)    -2381.
## 2 carat           8296.
## 3 color2          -540.
## 4 carat:color2   -1202.</code></pre>
<p>So, the intercepts and slopes differ. Why is that? First, their meanings changed.</p>
<p>Recall that in the two-predictor case the intercept is to be interpreted as 0 carat and E color. The slope for carat tells us the change in price for one carat. The slope for the treatment (our color J) then tells us that this color achieves a lower price per change in carat.</p>
<p>With the interaction present, these meanings change slightly.</p>
<p>The carat slope is now the slope only for the color E, and not the average effect of weight.</p>
<p>Similarly, the effect of <code>color.L</code> now only tracks the color difference for diamonds with a weight of 0 carat. It is no longer the average effect of the color change.</p>
<p>And now for the new coefficient: the interaction term. This tells us how to adjust the slopes for the color L. Here, because of the negative sign, this means that for the color L the slope is less steep than it is for our reference level.</p>
<p>This is what we call a <strong>simple effect</strong>: namely the influence of one predictor for only one level of another predictor. This is different from the <strong>main effects</strong> we got before.</p>
<p>Note also that for the case with two predictors with two levels each (and an interaction), each of the two predictors will be associated with two simple effects, namely one for each value of the other predictor. And the interaction represents the difference between these simple effects. If the interaction term is zero, the two simple effects are equal (and equal to the main effect).</p>
<p>The mental calculation we have to do is this: The carat slope for the other color is <span class="math inline">\(8296\)</span>. To get the slope for color L, we need to add the interaction term: <span class="math inline">\(8296 + (- 1202) = 7094\)</span>. That is, this color is less affected by an increase in weight, and thus achieves a lower price overall.</p>
<p>We can see this in the plots below as well (note that the individual data points do not change, only the representation of the data in the form of a line does; our model is different):</p>
<div class="figure" style="text-align: center">
<img src="figs/p_twopredint-1.png" alt="Comparison between (i) no interaction term and (ii) yes interaction term." width="100%" />
<p class="caption">
(#fig:p_twopredint)Comparison between (i) no interaction term and (ii) yes interaction term.
</p>
</div>
<p>Note that we can also add a further technique to make the output of the interaction term a little bit easier: We can center the carat predictor.</p>
<p>Recall that this changes the meaning of the intercept to the mean.</p>
<p>This then means that we have a changed interpretation of the color manipulation as well: It represents the difference between the two for the average value of carat in our dataset.</p>
<p>Arguably, this is easier to understand than thinking about diamonds with a weight of zero (the interpretation in our uncentered model).</p>
<p>Let’s look at this:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="4-regression.html#cb135-1" aria-hidden="true" tabindex="-1"></a>lm_diam_twopredint_c <span class="ot">&lt;-</span> diamonds_sub <span class="sc">%&gt;%</span></span>
<span id="cb135-2"><a href="4-regression.html#cb135-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">carat_c =</span> carat <span class="sc">-</span> <span class="fu">mean</span>(carat)) <span class="sc">%&gt;%</span></span>
<span id="cb135-3"><a href="4-regression.html#cb135-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(price <span class="sc">~</span> carat_c <span class="sc">*</span> color, .)</span>
<span id="cb135-4"><a href="4-regression.html#cb135-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb135-5"><a href="4-regression.html#cb135-5" aria-hidden="true" tabindex="-1"></a>lm_diam_twopredint_c <span class="sc">%&gt;%</span></span>
<span id="cb135-6"><a href="4-regression.html#cb135-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb135-7"><a href="4-regression.html#cb135-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 2
##   term           estimate
##   &lt;chr&gt;             &lt;dbl&gt;
## 1 (Intercept)       4009.
## 2 carat_c           8296.
## 3 color2           -1465.
## 4 carat_c:color2   -1202.</code></pre>
<p>Another way of going about this is to change the contast coding from treatment conding to sum coding. If we switch to sum coding, each coefficient for the sum-coded predictors represents the half of the difference between the two predictor levels. In other words, what we now have are <strong>main effects</strong>, rather than <strong>simple effects</strong>.</p>
<p>You can think of sum-coding for categorical variables as the analogue of centering (or standardizing, which subsumes centering) for continuous predictors.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="4-regression.html#cb137-1" aria-hidden="true" tabindex="-1"></a>diamonds_sub<span class="sc">$</span>color <span class="ot">&lt;-</span> <span class="fu">droplevels</span>(diamonds_sub<span class="sc">$</span>color)</span>
<span id="cb137-2"><a href="4-regression.html#cb137-2" aria-hidden="true" tabindex="-1"></a><span class="fu">contrasts</span>(diamonds_sub<span class="sc">$</span>color) <span class="ot">&lt;-</span> <span class="fu">contr.sum</span>(<span class="dv">2</span>)</span>
<span id="cb137-3"><a href="4-regression.html#cb137-3" aria-hidden="true" tabindex="-1"></a>diamonds_sub <span class="sc">%&gt;%</span></span>
<span id="cb137-4"><a href="4-regression.html#cb137-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">carat_c =</span> carat <span class="sc">-</span> <span class="fu">mean</span>(carat)) <span class="sc">%&gt;%</span></span>
<span id="cb137-5"><a href="4-regression.html#cb137-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(price <span class="sc">~</span> carat_c <span class="sc">*</span> color, <span class="at">data =</span> .) <span class="sc">%&gt;%</span></span>
<span id="cb137-6"><a href="4-regression.html#cb137-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span></span>
<span id="cb137-7"><a href="4-regression.html#cb137-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(term, estimate)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 2
##   term           estimate
##   &lt;chr&gt;             &lt;dbl&gt;
## 1 (Intercept)       3276.
## 2 carat_c           7695.
## 3 color1             733.
## 4 carat_c:color1     601.</code></pre>
<div class="alert alert-info">
<p><strong>Exercise</strong>: So far, we looked at the mixed cases, where one predictor is categorical and one is continuous. As an exercise, please compute (at least) two further linear models, each with two predictors of the same data type. In the case with two continuous predictors, you should think about centering or standardizing the predictors and try to think about the changes this choice induces. There’s no need to do an interaction analysis.</p>
<p>For the case with two categorical predictors, please include an interaction term in the model formula. You should also make a decision about what contrast coding scheme you want to follow.</p>
<p>For both, you should write a short description of the model you ran as well an interpretation of the modal coefficients.</p>
</div>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="3-anova.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="5-linear-mixed-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"search": {
"engine": "lunr",
"options": null
},
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"info": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
